### PR TITLE
Refinements

### PR DESCRIPTION
**Pull request by n9yty**
@Julusian This fixes a number of the open issues and incorporates feedback from sstaub. Updated documentation a bit as well. It also fixes a bug I didn't know was introduced in the conversion from the 2API to 3API, something I hadn't tested turned out to not be working.

### CODE REVIEW

**Comment by josephdadams** [comment]
Can you add yourself as a maintainer to manifest.json?

**Comment by n9yty** [comment]
@josephdadams Added.

**Comment by n9yty** [comment]
@Julusian Sorry to see this missed RC1 release, it fixes breaking bugs. I know you are quite busy, but if you can get this merged please.

**Comment by josephdadams** [comment]
Merged, updated package.json to remove a 'W' character from the version number, tagged a release, and put it into the beta builds

**Comment by n9yty** [comment]
@josephdadams Thanks for fixing the stray character. Oops. Thanks to the Bitfocus team for the help, support and encouragement as I ramped up to contribute on this project.

**Pull request merged**
