### PR TITLE
Rework for Companion v3 and minor tweaks

### PR DESCRIPTION
**Pull request by n9yty**
Hopefully all was done properly and this pull request will come through with changes for Companion v3 and minor tweaks (cue intensity and encoder wheel data).

### CODE REVIEW

**Comment by n9yty** [comment]
It was a nice idea on the encoder wheels, but as I moved this to my nomad station and started playing, it seems the wheel numbers change based on fixture type. So while the work I did "works" it isn't very usable perhaps.  I think probably it would be necessary to come up with the key values that are important, intensity, pan, tilt, zoom, etc, and parse the wheel labels and assign to distinct variables.

**Comment by n9yty** [comment]
Hmmm... Seems there might be more afoot. I didn't have a full test station set up, I was watching for values to update, variables to be available, etc., but in testing seems something may not be 100%. I'll come back at it soon, if I need a new pull request I can do that, unless I can patch this one. Dunno. But it is a solid start anyway.

**Comment by Julusian** [comment]
Thanks, I've done some cleanup of some issues I found. Im not sure if you were ready for this to be merge, but github forced me to do it by not letting me push some of my changes to your branch..

I don't have the device to test with, could you give it a try and make sure I didnt break anything?

**Comment by n9yty** [comment]
Thanks. I reply want the right person to do this, not really fluent in JavaScript and never looked at companion modules before. The fact it worked is impressive. :)  If I understand correctly (yes, also don’t know git very well) my repo is now irrelevant to the pull request so I can start over with my edits from where it is now? I’ll start running some tests and if I think of other changes I can do another pull request (maybe do a branch first this time). Thanks for the encouragement to get it done, I hope it proves useful.

**Pull request merged**
